--- 
knit: "bookdown::render_book"
title: "Source code and supporting information for _Using BirdNET to identify mixed-species flocking bird species in the Western Ghats_"
author:
    - Vijay Ramesh
    - Priyanka Hariharan
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    fig_caption: yes
  bookdown::pdf_document2:
    documentclass: scrreprt
    toc-depth: 1
    secnumdepth: 2
    geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
biblio-style: apalike
link-citations: yes
github-repo: vjjan91/mixed-species-flock-acoustics
---

# Introduction  

This is the readable version that showcases analyses using BirdNET to carry out automated identification of bird species that participate in mixed-species flocks. In this repository, we focus our analyses on thirteen species alone that are considered to be important species in a flock.    

The list of 13 species include: 
- Indian White-eye  
- Greenish Warbler  
- Orange Minivet  
- Velvet-fronted Nuthatch  
- Yellow-browed Bulbul  
- Greater Racket-tailed Drongo  
- Ashy Drongo  
- Indian Yellow Tit  
- Green Warbler  
- Large-billed Leaf Warbler  
- Gray-headed Canary-Flycatcher  
- Nilgiri Flycatcher  
- Brown-cheeked Fulvetta  

Using BirdNET Analyzer GUI v2.0.0 and previously written code and steps [here](https://vjjan91.github.io/paired-pointCount-acoustics/exploring-outputs-from-birdnet.html), we use previously set thresholds (except for three species, the Gray-headed Canary-Flycatcher, Nilgiri Flycatcher and Ashy Drongo) to filter all audio detections with a probability of detection of 0.95. Upon running analyses, the model did not detect any instances of the Gray-headed Canary-Flycatcher or the Nilgiri Flycatcher. The model did not perform well enough for us to set thresholds for the Ashy Drongo and all instances were manually verified.   

## Attribution  

Please contact the following in case of interest in the project.  

- Vijay Ramesh (repo maintainer)
    - Postdoctoral Research Associate, Cornell Lab of Ornithology  

## Data access  

The data used in this work will be archived on Zenodo.  

## Data processing  

The data processing for this project is described in the following sections. Navigate through them using the links in the sidebar.      
